# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://vcp-kirchhain.de'
baseurl: ''
title: 'VCP Stamm Kirchhain'
description: 'Der VCP Kirchhain ist ein Pfadfinderstamm in Kirchhain (Kreis Marburg-Biedenkopf) vom Verband Christlicher Pfadfinderinnen und Pfadfinder.'
permalink: pretty
logo: "/assets/vcp.svg"

# Pagination
paginate: 5
paginate_path: aktuelles/page:num

# Header nav
navigation_header:
  Home: /
  Aktuelles: /aktuelles/
  Gruppen: /gruppen/
  Gruppenleiter*innen: /gruppenleiterinnen/

# Footer nav
navigation_footer:
  Datenschutzerklärung: "/datenschutz/"
  Impressum: "/impressum/"
  Nach oben: "#top"

# Collections
collections:
  posts:
    output: true
    feature_text: "# Aktuelles von uns"
    feature_image: "/assets/header/stockbrot.jpg"
